name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: CMake Generate
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}

      - name: CMake Build
        run: cmake --build ${{ github.workspace }}/build --target ember

      - name: CMake Tests
        run: ctest --build-dir ${{ github.workspace }}/build --output-on-failure

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: CMake Generate
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}

      - name: CMake Build
        run: cmake --build ${{ github.workspace }}/build --target ember

      - name: CMake Tests
        run: ctest --build-dir ${{ github.workspace }}/build --output-on-failure